version: "3.9"
services:
    php:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf